# Generated by Django 3.0.2 on 2020-01-10 16:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True)),
                ('wherefrom', models.CharField(max_length=150)),
                ('whereto', models.CharField(max_length=150)),
                ('when', models.DateTimeField()),
                ('photo', models.ImageField(blank=True, upload_to='')),
                ('body', models.TextField(blank=True, db_index=True)),
                ('date_pub', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='AdDriver',
            fields=[
                ('ad_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='user.Ad')),
                ('car_photo', models.ImageField(blank=True, upload_to='')),
                ('active', models.BooleanField(default=True)),
                ('history', models.CharField(max_length=150)),
            ],
            bases=('user.ad', models.Model),
        ),
        migrations.AddField(
            model_name='ad',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='ads', to='user.Tag'),
        ),
    ]
