# Generated by Django 3.0.2 on 2020-01-11 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ad',
            options={'ordering': ['-date_pub']},
        ),
        migrations.AddField(
            model_name='addriver',
            name='car_info',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='addriver',
            name='active',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='addriver',
            name='history',
            field=models.CharField(max_length=255),
        ),
    ]
